# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# Activate a set of recommended lints for Flutter apps, packages, and plugins
# designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized below to disable
  # rules from `package:flutter_lints/flutter.yaml` or enable additional rules.
  # See https://dart.dev/lints for full documentation.
  rules:
    # Example: Uncomment to disable the `avoid_print` rule
    # avoid_print: false

    # Example: Uncomment to enable the `prefer_single_quotes` rule
    # prefer_single_quotes: true
