name: flutter_brotcattle
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Your packages
  http: ^1.5.0
  telegram_web_app: ^0.3.3
  jwt_decode: ^0.3.1
  universal_html: ^2.2.4
  intl: ^0.20.2
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.5.0

flutter:
  uses-material-design: true
